### PR TITLE
WEB-7614: Node v6 base image

### PR DESCRIPTION
**Pull request by wallylawless**
* Uses the official Node.js v6 base image on Alpine
* Updated release.sh script to work with new Dockerfile format

### CODE REVIEW

**Review by pbitty — CHANGES_REQUESTED** [review]
We talked offline.  I suggested skipping our own intermediate image, referencing the `node:6.10.3-alpine` image directly downstream.

**Comment by wallylawless** [comment]
@pbitty I think I'm going to keep with maintaining our own image, specifically since I'm looking into including this module: https://www.npmjs.com/package/@newrelic/native-metrics which needs to be compiled on the host machine. 

We have data going to New Relic already for our one canary box, but this native module will give us much deeper information like CPU/memory usage, GC timings etc.. Should help us keep an eye on things like memory leaks that we currently don't have a good way to trace.

**Comment by pbitty** [comment]
OOoh,  that sounds amazing!  👍

**Comment by jharlap** [comment]
Too old: closed.

**Pull request closed without merging**
